#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    a,b,c = list(map(int, input().split()))
    if a == b == c:
        print(YES)
    elif a + b == c or b + c == a or c + a == b:
        print(YES)
    else:
        print(NO)
    pass

if __name__ == '__main__':
    main()
