#!/usr/bin/env python3


# Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    H,W,X,Y = list(map(int, input().split()))
    x = X - 1
    y = Y - 1
    rows = []
    for _ in range(H):
        rows.append(list(input()))

    directions = list(input())
    houseCount = 0

    for direction in directions:
        if direction == 'U':
            if rows[x-1][y] == '#':
                continue
            x -= 1
        elif direction == 'D':
            if rows[x+1][y] == '#':
                continue
            x += 1
        elif direction == 'L':
            if rows[x][y-1] == '#':
                continue
            y -= 1
        elif direction == 'R':
            if rows[x][y+1] == '#':
                continue
            y += 1

        if rows[x][y] == '@':
            houseCount += 1
            rows[x][y] = '.'
    print(f'{x + 1} {y + 1} {houseCount}')
    pass

if __name__ == '__main__':
    main()
